version: '4'

services:

  server:
    container_name: server
    hostname: server
    image: nginx:stable-bullseye-perl
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - sublate
    ports:
      - '9999:9999'
    depends_on:
      - stack
  
  database:
    container_name: database
    hostname: ${POSTGRES_HOST}
    image: postgres:16.2-bullseye
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - sublate
    ports:
      - '5432:5432'

  stack:
    container_name: stack
    hostname: stack
    build:
       context: .
       dockerfile: ./docker/Dockerfile
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./:/app
    networks:
      - sublate
    expose:
      - "8000"
    command: 
      - 'sh'
      - '-c'
      - |
        poetry run python manage.py makemigrations
        poetry run python manage.py migrate
        poetry run python manage.py runserver 0.0.0.0:8000
#        tail -f /dev/null
    depends_on:
      - database

networks:
  sublate:
    external: true
